name       : geany
version    : '1.33'
release    : 14
source     :
    - http://download.geany.org/geany-1.33.tar.gz : e59ba42a6eeb2d335160e304c5875f8ae54db4f97bc7744e34f9ad0cf3d0779f
license    : GPL-2.0
component  : editor
summary    : Small and lightweight integrated development environment
description: |
    Geany is a small and lightweight integrated development environment,
    designed to be fast and require minimal dependencies. It has syntax
    highlighting, code folding, autocomplete, a build system, and a plugin
    system.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - python-lxml
rundeps    :
    - libvte
setup      : |
    %configure --docdir=/usr/share/doc/geany \
               --enable-gtk3 \
               PYTHON=python3
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
