name        : geany
version     : 1.25
release     : 4
source     :
    - http://download.geany.org/geany-1.25.tar.bz2 : 8ee41da28cead8c94d433e616d7ababa81727c63e9196ca6758ade3af14a49ef
license     : GPL-2.0
summary     : Small and lightweight integrated development environment in GTK2
builddeps   :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(cairo)
    - pkgconfig(atk)
description : |
    Geany is a small and lightweight integrated development environment written in GTK2, designed to be fast and require minimal dependencies. It has syntax highlighting, code folding, autocomplete, a build system, and a plugin system.
clang      : no
setup      : |
    %configure --docdir=/usr/share/doc/geany
build      : |
    %make
install    : |
    %make_install
