name        : geany
version     : 1.29
release     : 8
source     :
    - http://download.geany.org/geany-1.29.tar.bz2 : 394307596bc908419617e4c33e93eae8b5b733dfc8d01161677b8cbd3a4fb20f
license     : GPL-2.0
component   : editor
summary     : Small and lightweight integrated development environment in GTK2
builddeps   :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(cairo)
    - pkgconfig(atk)
rundeps     :
    - vte2
description : |
    Geany is a small and lightweight integrated development environment written in GTK2, designed to be fast and require minimal dependencies. It has syntax highlighting, code folding, autocomplete, a build system, and a plugin system.
clang      : no
setup      : |
    %configure --docdir=/usr/share/doc/geany
build      : |
    %make
install    : |
    %make_install
