name       : geany
version    : 1.34
release    : 16
source     :
    - https://download.geany.org/geany-1.34.tar.gz : 9c4052042ac4f8664d182c28e6aaa05edd4c41dcfa2d3a9754f5cf7d475f3339
license    : GPL-2.0-or-later
component  : editor
summary    : Small and lightweight integrated development environment
description: |
    Geany is a small and lightweight integrated development environment,
    designed to be fast and require minimal dependencies. It has syntax
    highlighting, code folding, autocomplete, a build system, and a plugin
    system.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - python-lxml
rundeps    :
    - libvte
setup      : |
    %configure --docdir=/usr/share/doc/geany \
               --enable-gtk3 \
               PYTHON=python3
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check || :
