name       : geany
version    : '1.38'
release    : 27
source     :
    - https://github.com/geany/geany/releases/download/1.38.0/geany-1.38.tar.gz : e91e903924b993b79ef88f33708372dc7c79aee78e15a02e728338695e9dc155
license    : GPL-2.0-or-later
component  : editor
summary    : Small and lightweight integrated development environment
description: |
    Geany is a small and lightweight integrated development environment,
    designed to be fast and require minimal dependencies. It has syntax
    highlighting, code folding, autocomplete, a build system, and a plugin
    system.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - python-docutils
    - python-lxml
rundeps    :
    - libvte
setup      : |
    %patch -p1 < $pkgfiles/0001-Set-the-correct-terminal.patch
    %autogen --docdir=/usr/share/doc/geany \
             --enable-gtk3 \
             PYTHON=python3
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/share/doc/geany/{AUTHORS,COPYING,ChangeLog,NEWS,README,ScintillaLicense.txt,THANKS,TODO,manual.txt}
    rm $installdir/usr/share/geany/GPL-2
check      : |
    %make check || :
