name        : geany
version     : 1.24.1
release     : 3
source      :
    - http://download.geany.org/geany-1.24.1.tar.gz : 8aa5dbf94b5252fce2ba504b47addb047a076fe44f11a08be45dc59e7ac318ba
homepage    : http://www.geany.org
license     : GPL-2.0
summary     : Small and lightweight integrated development environment in GTK2
builddeps   :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(cairo)
    - pkgconfig(atk)
description : |
    Geany is a small and lightweight integrated development environment written in GTK2, designed to be fast and require minimal dependencies. It has syntax highlighting, code folding, autocomplete, a build system, and a plugin system.
clang      : no
setup      : |
    %configure --docdir=/usr/share/doc/geany
build      : |
    %make
install    : |
    %make_install
